title: Fundacja Nowe Teraz
description: Edukujemy, wspieramy i inspirujemy wspólne działanie osób w trudnej sytuacji życiowej.

url: https://www.noweteraz.pl

author: Fundacja Nowe Teraz

logo: /assets/img/logo-www-150x150.png

locale: pl_PL

future: false 

timezone: Europe/Warsaw

social:
  name: Fundacja Nowe Teraz
  links:
    - https://www.facebook.com/wykluczenipl
    - https://www.youtube.com/channel/UCIp9Zws489eOnFag8fdxVQQ
    
contact_form: https://docs.google.com/forms/d/e/1FAIpQLSdxXd_IdTOxOK2iEnSvy55U9lFWKWjTpJeby_zufZ8buYPUuQ/viewform

volunteer_form: https://docs.google.com/forms/d/e/1FAIpQLSfy6h5cRm5Ht1tGrRK8nZ-WwBYydBQHffhrpSwI5zL-Im0SUA/viewform

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
excerpt_separator: |2+

google_analytics: UA-133950974-1
facebook: "https://www.facebook.com/fundacja.nowe.teraz"
# youtube: "https://www.youtube.com/channel/UCIp9Zws489eOnFag8fdxVQQ"

collections:
  posts:
    output: true
  pages:
    output: true
  shop:
    output: true
    permalink: /sklep-charytatywny/:name/

defaults:
- scope:
    path: ""
    type: "posts"
  values:
    permalink: "/blog/:title/"
    layout: "post"
- scope:
    path: "/assets/img/uploads/files/*.pdf"
  values:
    sitemap: false
- scope:
    path: _shop
  values:
      layout: shop

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js

header_nav_left:
  Strona główna: "/"
  O fundacji: "/o-fundacji/"
  Programy: "/programy/"
  Projekty: "/projekty/"

header_nav_right:
  Wesprzyj nas: "/wspieram/"
  Blog: "/blog/"
  Sklep: "/sklep-charytatywny/"
  Galeria: "https://galeria.noweteraz.pl"
  Kontakt: "/kontakt/"

footer_nav:
  Sklep: "/sklep-charytatywny/"
  Galeria: "https://galeria.noweteraz.pl"
  Wolontariat: "https://wolontariat.noweteraz.org"
  Wesprzyj nas: "/wspieram/"
  Kontakt: "/kontakt/"

terms_nav:
  Polityka prywatności: /polityka-prywatnosci/
  Regulaminy: /regulamin/

address:
  addressLocality: Warszawa
  streetAddress: Zielna 39
  addressRegion: Mazowieckie
  postalCode: 00-108
  addressCountry: Polska
  telephone: +48 574-662-644
  e-mail: sekretariat@noweteraz.pl

legal:
  ceo: Andrzej Grudziński
  krs: 0000495968
  nip: 5252585787
  regon: 147116250
  bank: PKO BP
  account: 07 1020 1013 0000 0102 0423 4647

geo:
  latitude: "54.4180200"
  longitude: "18.5659700"
  map: "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d9773.557908550833!2d21.006197!3d52.236309!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xda3e3d69d34cbba5!2sFundacja%20Nowe%20Teraz!5e0!3m2!1spl!2spl!4v1613652594147!5m2!1spl!2spl"

scripts_lazyload: |-

  <script src="/assets/js/lazysizes.min.js" async=""></script>

